# Generated by Django 5.1.5 on 2025-04-12 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('ministry', models.CharField(max_length=100)),
                ('sector', models.CharField(max_length=100)),
                ('launch_year', models.CharField(max_length=10)),
                ('cs_css', models.CharField(max_length=10)),
                ('summary', models.TextField()),
                ('wiki_link', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
