# Generated by Django 5.1.5 on 2025-04-12 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0002_scheme'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchemeRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('age', models.IntegerField()),
                ('occupation', models.CharField(max_length=100)),
                ('income', models.IntegerField()),
                ('category', models.CharField(default='General', max_length=50)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('recommended_schemes', models.TextField()),
            ],
        ),
    ]
